var g0 = {
  $: ['Html'],
  Html: [[{ t: 1, s: 'Node', f: 3 }]],
  Node: [
    [{ t: 1, s: 'Element', f: 0 }],
    [{ t: 1, s: 'Text', f: 0 }]
  ],
  Element: [[{ t: 1, s: 'Head', f: 0 }, { t: 1, s: 'Node', f: 3 }, { t: 1, s: 'Tail', f: 1 }]],
  Head: [[{ t: 0, s: '<', f: 0 }, { t: 1, s: 'Tag', f: 16 }, { t: 1, s: 'Attributes', f: 1 }, { t: 0, s: '>', f: 0 }]],
  Tag: [[{ t: 0, s: '\\w+', f: 0 }]],
  Attributes: [[{ t: 1, s: 'Attribute', f: 3 }]],
  Attribute: [[{ t: 0, s: '\\s+', f: 0 }, { t: 1, s: 'AttrKey', f: 0 }, { t: 1, s: 'AttrInit', f: 1 }]],
  AttrKey: [[{ t: 0, s: '[^=>\\s]+', f: 0 }]],
  AttrInit: [[{ t: 0, s: '=', f: 0 }, { t: 1, s: 'AttrExpr', f: 1 }]],
  AttrExpr: [
    [{ t: 0, s: '"', f: 0 }, { t: 0, s: '[^"]*', f: 0, r: 'AttrValue' }, { t: 0, s: '"', f: 0 }],
    [{ t: 0, s: "'", f: 0 }, { t: 0, s: "[^']*", f: 0, r: 'AttrValue' }, { t: 0, s: "'", f: 0 }],
    [{ t: 0, s: '[^>\\s]*', f: 0, r: 'AttrValue' }]
  ],
  Tail: [[{ t: 0, s: '\\</', f: 0 }, { t: 1, s: 'Tag', f: 32 }, { t: 0, s: '>', f: 0 }]],
  Text: [[{ t: 0, s: '(?:[^<]|<[^\\w/])+', f: 0 }]]
};

var g1 = {
  $: [' ', 'Html', 'Node', 'Element', 'Head', 'Tag', 'Attributes', 'Attribute', 'AttrKey', 'AttrInit', 'AttrExpr', 'AttrValue', 'Tail', 'Text'],
  Html: 1,
  Node: 2,
  Element: 3,
  Head: 4,
  Tag: 5,
  Attributes: 6,
  Attribute: 7,
  AttrKey: 8,
  AttrInit: 9,
  AttrExpr: 10,
  AttrValue: 11,
  Tail: 12,
  Text: 13,
  1: [[[2, 3]]],
  2: [[[3]], [[13]]],
  3: [[[4], [2, 3], [12, 1]]],
  4: [[['<'], [5, 16], [6, 1], ['>']]],
  5: [[['\\w+']]],
  6: [[[7, 3]]],
  7: [[['\\s+'], [8], [9, 1]]],
  8: [[['[^=>\\s]+']]],
  9: [[['='], [10, 1]]],
  10: [[['"'], ['[^"]*', -11], ['"']], [["'"], ["[^']*", -11], ["'"]], [['[^>\\s]*', -11]]],
  12: [[['\\</'], [5, 32], ['>']]],
  13: [[['(?:[^<]|<[^\\w/])+']]]
};

var g2 = {
  $: [' ', 'Html', 'Node', 'Element', 'Head', 'Tag', 'Attributes', 'Attribute', 'AttrKey', 'AttrInit', 'AttrExpr', 'AttrValue', 'Tail', 'Text'],
  Html: 1,
  Node: 2,
  Element: 3,
  Head: 4,
  Tag: 5,
  Attributes: 6,
  Attribute: 7,
  AttrKey: 8,
  AttrInit: 9,
  AttrExpr: 10,
  AttrValue: 11,
  Tail: 12,
  Text: 13,
  0: /\s+|()/g,
  1: [[[2, 3]]],
  2: [[[3]], [[13]]],
  3: [[[4], [2, 3], [12, 1]]],
  4: [[[14], [5, 16], [6, 1], [15]]],
  5: /\w+|()/g,
  6: [[[7, 3]]],
  7: [[[16], [8], [9, 1]]],
  8: /[^=>\s]+|()/g,
  9: [[[17], [10, 1]]],
  10: [[[18], [19, -11], [18]], [[20], [21, -11], [20]], [[22, -11]]],
  12: [[[23], [5, 32], [15]]],
  13: /(?:[^<]|<[^\w/])+|()/g,
  14: /<|()/g,
  15: />|()/g,
  16: /\s+|()/g,
  17: /=|()/g,
  18: /"|()/g,
  19: /[^"]*|()/g,
  20: /'|()/g,
  21: /[^']*|()/g,
  22: /[^>\s]*|()/g,
  23: /\<\/|()/g,
};